FROM node:24-bookworm AS build

ARG VITE_API_BASE_URL=http://localhost:8080/api/graph
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80  
CMD ["nginx", "-g", "daemon off;"]