export const DEFAULT_RADIUS_SIZE = 20;
export const DEFAULT_FACILITY_WIDTH = Math.floor(DEFAULT_RADIUS_SIZE*Math.sqrt(2)*0.95);
export const DEFAULT_FACILITY_HEIGHT = Math.floor(DEFAULT_RADIUS_SIZE*Math.sqrt(2)*0.95);
export const DEFAULT_VIEWBOX_TOP_PADDING = 10;
export const DEFAULT_VIEWBOX_RIGHT_PADDING = 10;
